version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lol666gg
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always
    
  