FROM node:16

WORKDIR /app

RUN apt-get update && apt-get install -y netcat

COPY package*.json ./

RUN npm install

RUN npm install -g prisma

COPY . .

WORKDIR /app/db

RUN npx prisma generate


WORKDIR /app

COPY entrypoint.sh /app/

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["node", "app.js"]
